spring:
  messages.basename: i18n.login #配置文件的真实地址
  mvc.date-format: yyyy-MM-dd  #自定义时间格式
  thymeleaf:
    cache: false #关闭模板引擎的缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: yelinlan
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5 #初始化大小
      minIdle: 5 #最小值
      maxActive: 20 #最大值
      maxWait: 60000 #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20 #最大PSCache连接
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      web-stat-filter: # 配置StatFilter
        enabled: true #默认为false，设置为true启动
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: #配置StatViewServlet http://localhost:8080/yll/druid/index.html
        url-pattern: "/druid/*"
        allow: 127.0.0.1 #允许那些ip
        login-username: admin
        login-password: 123456
        deny: 192.168.1.102 #禁止那些ip
        reset-enable: true #是否可以重置
        enabled: true #启用
  #访问url访问路径
server:
  servlet:
    context-path: /yll
mybatis:
  type-aliases-package: com.yll.springbootweb.pojo
  mapper-locations: classpath:mapper/*.xml

